apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ci-cd-final-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-final-pipeline
  params:
    - name: repo-url
      value: https://github.com/jgspableo/ci-cd-final-project.git
    - name: revision
      value: main
    - name: image-reference
      value: image-registry.openshift-image-registry.svc:5000/sn-labs-jgsepableo/ci-cd-final-project:latest
    - name: app-name
      value: ci-cd-final-project
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc